# Generated by Django 5.2.8 on 2025-11-14 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(help_text='URL of the suggested image')),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Image description')),
                ('source', models.CharField(choices=[('unsplash', 'Unsplash'), ('pixabay', 'Pixabay'), ('pexels', 'Pexels'), ('user_upload', 'User Upload')], help_text='Where image came from', max_length=50)),
                ('relevance_score', models.FloatField(default=0.0, help_text='How relevant to blog (0-1)')),
                ('suggested_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Suggestion timestamp')),
                ('is_selected', models.BooleanField(default=False, help_text='Was this image used')),
                ('blog_post', models.ForeignKey(help_text='Blog post', on_delete=django.db.models.deletion.CASCADE, related_name='image_suggestions', to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Image Suggestions',
                'ordering': ['-relevance_score', '-suggested_at'],
            },
        ),
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_text', models.TextField(help_text='Original user prompt/idea')),
                ('generated_content', models.TextField(help_text='AI-generated content')),
                ('content_type', models.CharField(choices=[('blog_generation', 'Blog Generation'), ('content_enhancement', 'Content Enhancement'), ('translation', 'Translation'), ('image_description', 'Image Description')], help_text='Type of AI generation', max_length=50)),
                ('ai_model_used', models.CharField(default='openai-gpt-3.5', help_text='Which AI model was used', max_length=100)),
                ('enhancement_level', models.CharField(blank=True, default='professional', help_text='Enhancement style (funny, professional, formal, etc.)', max_length=50)),
                ('target_language', models.CharField(blank=True, help_text='Target language for translation', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Generation timestamp')),
                ('usage_tokens', models.IntegerField(default=0, help_text='Tokens used for API call')),
                ('author', models.ForeignKey(help_text='User who created the prompt', on_delete=django.db.models.deletion.CASCADE, related_name='ai_prompts', to=settings.AUTH_USER_MODEL)),
                ('blog_post', models.ForeignKey(blank=True, help_text='Associated blog post (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_prompts', to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'AI Prompts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['author', 'content_type'], name='core_aiprom_author__dc5054_idx'), models.Index(fields=['-created_at'], name='core_aiprom_created_b8be1a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentSentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], help_text='Overall sentiment', max_length=20)),
                ('confidence_score', models.FloatField(help_text='Confidence score (0-1)')),
                ('sentiment_type', models.CharField(choices=[('improvement', 'Improvement Suggestion'), ('appreciation', 'Appreciation'), ('feedback', 'Detailed Feedback'), ('question', 'Question'), ('criticism', 'Criticism'), ('other', 'Other')], default='other', help_text='Type of sentiment content', max_length=50)),
                ('polarity', models.FloatField(default=0.0, help_text='Polarity score (-1 to 1)')),
                ('subjectivity', models.FloatField(default=0.0, help_text='Subjectivity score (0 to 1)')),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Analysis timestamp')),
                ('analysis_model', models.CharField(default='textblob', help_text='Which analysis model was used', max_length=100)),
                ('comment', models.OneToOneField(help_text='Associated comment', on_delete=django.db.models.deletion.CASCADE, related_name='sentiment', to='blog.comment')),
            ],
            options={
                'verbose_name_plural': 'Comment Sentiments',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['sentiment'], name='core_commen_sentime_33501c_idx'), models.Index(fields=['sentiment_type'], name='core_commen_sentime_be5c4f_idx')],
            },
        ),
    ]
