# Generated by Django 5.2.8 on 2025-11-14 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='User biography', max_length=500, null=True)),
                ('profile_image', models.ImageField(blank=True, help_text='User profile picture', null=True, upload_to='profiles/')),
                ('follower_count', models.IntegerField(default=0, help_text='Number of followers')),
                ('following_count', models.IntegerField(default=0, help_text='Number of users following')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Account creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last profile update')),
                ('user', models.OneToOneField(help_text='Link to Django User model', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ['-created_at'],
            },
        ),
    ]
