# Generated by Django 5.2.8 on 2025-11-14 10:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog post title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly title', unique=True)),
                ('content', models.TextField(help_text='Main blog content')),
                ('excerpt', models.TextField(help_text='Short preview of blog', max_length=500)),
                ('featured_image', models.ImageField(blank=True, help_text='Main blog image', null=True, upload_to='blog_images/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Publication date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', help_text='Current status', max_length=20)),
                ('category', models.CharField(blank=True, help_text='Blog category/tags', max_length=100)),
                ('likes_count', models.IntegerField(default=0, help_text='Total likes')),
                ('dislikes_count', models.IntegerField(default=0, help_text='Total dislikes')),
                ('comments_count', models.IntegerField(default=0, help_text='Total comments')),
                ('views_count', models.IntegerField(default=0, help_text='Total views')),
                ('author', models.ForeignKey(help_text='Blog author', on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Comment text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Comment creation date')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last modification')),
                ('is_approved', models.BooleanField(default=True, help_text='Is comment approved')),
                ('author', models.ForeignKey(help_text='Comment author', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Parent comment (for nested replies)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='blog.comment')),
                ('post', models.ForeignKey(help_text='Blog post being commented on', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blogpost')),
            ],
            options={
                'verbose_name_plural': 'Comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike')], help_text='Type of interaction', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Interaction date')),
                ('post', models.ForeignKey(help_text='Blog post', on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='blog.blogpost')),
                ('user', models.ForeignKey(help_text='User who interacted', on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Post Interactions',
            },
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['slug'], name='blog_blogpo_slug_361555_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['author', 'status'], name='blog_blogpo_author__e8757b_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpost',
            index=models.Index(fields=['-created_at'], name='blog_blogpo_created_2e77d7_idx'),
        ),
        migrations.AddIndex(
            model_name='postinteraction',
            index=models.Index(fields=['post', 'interaction_type'], name='blog_postin_post_id_9d4d50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='postinteraction',
            unique_together={('post', 'user', 'interaction_type')},
        ),
    ]
